### PR TITLE
Win compilation fix

### PR DESCRIPTION
**Pull request by VaitkusM**

### CODE REVIEW

**Review by salvipeter — CHANGES_REQUESTED** [review]
The two new definitions can go in the same `add_definition` as the one for Qt6 widgets.
Why is `windows.h` needed?

**Comment by VaitkusM** [comment]
> The two new definitions can go in the same `add_definition` as the one for Qt6 widgets.

PR has been changed accordingly.

> Why is `windows.h` needed?

New version uses only the required defines, instead of windows.h.

**Review by salvipeter — COMMENTED** [review]
Better, but since `windows.h` is no longer included, `NOMINMAX` can also be deleted, right?

**Comment by VaitkusM** [comment]
> Better, but since `windows.h` is no longer included, `NOMINMAX` can also be deleted, right?

Indeed, PR updated.

**Review by salvipeter — APPROVED** [review]
OK, thanks!

**Pull request merged**
